version: '3.1'
services:
    kibana:
        image: kibana
        ports:
            - 5601:5601
    elasticsearch:
        image: elasticsearch:alpine
        ports:
            - 9300:9300
            - 9200:9200
    mongo:
        image: mongo
        ports:
            - 27017:27017
